// productosService.js - Servicio para la gestión de productos en Masarepas
export let mockProductos = [
  {
    id_producto: 1,
    nombre: "Arepa de Chócolo con Queso x5 und",
    descripcion: "Paquete de 5 arepas de maíz chócolo tierno con queso campesino y mantequilla",
    id_categoria: 1,
    id_ficha: 1,
    id_proveedor: 1,
    precio_venta: 8500,
    imagen_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 450,
    stock_minimo: 100,
    fecha_vencimiento: "2026-09-25",
    estado: "activo",
  },
  {
    id_producto: 2,
    nombre: "Arepa Telita Tradicional x10 und",
    descripcion: "Paquete de 10 arepas telitas delgadas de puro maíz blanco precocido",
    id_categoria: 2,
    id_ficha: 2,
    id_proveedor: 1,
    precio_venta: 6000,
    imagen_url: "https://images.unsplash.com/photo-1710018349908-39d998a519b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 1200,
    stock_minimo: 300,
    fecha_vencimiento: "2026-09-28",
    estado: "activo",
  },
  {
    id_producto: 3,
    nombre: "Arepa Rellena de Queso Doble Crema x5 und",
    descripcion: "Arepas semigruesas rellenas con abundante queso doble crema hilado",
    id_categoria: 3,
    id_ficha: 3,
    id_proveedor: 2,
    precio_venta: 11000,
    imagen_url: "https://images.unsplash.com/photo-1587603366933-aa6947174c65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 850,
    stock_minimo: 150,
    fecha_vencimiento: "2026-10-15",
    estado: "activo",
  },
  {
    id_producto: 4,
    nombre: "Arepa Santandereana con Chicharrón x5 und",
    descripcion: "Arepa artesanal con trozos de chicharrón crocante y maíz pelado",
    id_categoria: 4,
    id_ficha: 4,
    id_proveedor: 10,
    precio_venta: 9500,
    imagen_url: "https://images.unsplash.com/photo-1644753787067-d62ae70f303d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 320,
    stock_minimo: 100,
    fecha_vencimiento: "2026-09-30",
    estado: "activo",
  },
  {
    id_producto: 5,
    nombre: "Arepa de Yuca con Queso Costeño x5 und",
    descripcion: "Arepa elástica elaborada con yuca fresca seleccionada y queso costeño",
    id_categoria: 7,
    id_ficha: 5,
    id_proveedor: 14,
    precio_venta: 10500,
    imagen_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 280,
    stock_minimo: 80,
    fecha_vencimiento: "2026-10-05",
    estado: "activo",
  },
  {
    id_producto: 6,
    nombre: "Arepa Integral con Chía y Linaza x5 und",
    descripcion: "Arepa saludable alta en fibra natural, baja en grasa y sin sal añadida",
    id_categoria: 6,
    id_ficha: 6,
    id_proveedor: 5,
    precio_venta: 7800,
    imagen_url: "https://images.unsplash.com/photo-1509722747041-616f39b57569?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 410,
    stock_minimo: 100,
    fecha_vencimiento: "2026-10-12",
    estado: "activo",
  },
  {
    id_producto: 7,
    nombre: "Arepa Paisa Asada Redonda x10 und",
    descripcion: "Tradicional arepa paisa delgada para asar y consumir caliente con mantequilla",
    id_categoria: 2,
    id_ficha: 8,
    id_proveedor: 1,
    precio_venta: 5500,
    imagen_url: "https://images.unsplash.com/photo-1625605927823-7f10eaab7927?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 1500,
    stock_minimo: 350,
    fecha_vencimiento: "2026-09-29",
    estado: "activo",
  },
  {
    id_producto: 8,
    nombre: "Masa de Maíz Blanco para Empanadas x2 kg",
    descripcion: "Bloque de masa fresca suave y lista para armar empanadas y tamales",
    id_categoria: 5,
    id_ficha: 7,
    id_proveedor: 1,
    precio_venta: 8000,
    imagen_url: "https://images.unsplash.com/photo-1574484284002-952d92456975?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 620,
    stock_minimo: 120,
    fecha_vencimiento: "2026-09-22",
    estado: "activo",
  },
  {
    id_producto: 9,
    nombre: "Peto de Maíz Cocido Listo x1 kg",
    descripcion: "Maíz peto blanco cocido en su punto, ideal para mazamorra y sopas",
    id_categoria: 5,
    id_ficha: null,
    id_proveedor: 1,
    precio_venta: 4500,
    imagen_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 340,
    stock_minimo: 60,
    fecha_vencimiento: "2026-10-20",
    estado: "activo",
  },
  {
    id_producto: 10,
    nombre: "Arepa de Queso Tipo Boyacense x5 und",
    descripcion: "Arepa dulce con harina de maíz amarillo y cuajada fresca horneada",
    id_categoria: 1,
    id_ficha: 1,
    id_proveedor: 2,
    precio_venta: 9200,
    imagen_url: "https://images.unsplash.com/photo-1644753787071-8933b5daed2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 510,
    stock_minimo: 110,
    fecha_vencimiento: "2026-09-27",
    estado: "activo",
  },
  {
    id_producto: 11,
    nombre: "Arepa con Queso Mozzarella Gratinable x5 und",
    descripcion: "Arepa de maíz blanco con centro de queso mozzarella de alta elasticidad",
    id_categoria: 3,
    id_ficha: 3,
    id_proveedor: 2,
    precio_venta: 11500,
    imagen_url: "https://images.unsplash.com/photo-1587603366933-aa6947174c65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 680,
    stock_minimo: 140,
    fecha_vencimiento: "2026-10-18",
    estado: "activo",
  },
  {
    id_producto: 12,
    nombre: "Arepa HORECA Institucional x50 und",
    descripcion: "Caja institucional de 50 arepas medianas para asaderos y restaurantes",
    id_categoria: 8,
    id_ficha: 2,
    id_proveedor: 1,
    precio_venta: 26000,
    imagen_url: "https://images.unsplash.com/photo-1625605927823-7f10eaab7927?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 180,
    stock_minimo: 40,
    fecha_vencimiento: "2026-10-02",
    estado: "activo",
  },
  {
    id_producto: 13,
    nombre: "Arepa de Chócolo Mini Cocktail x20 und",
    descripcion: "Bocado dulce cocktail para eventos, recepciones y pasabocas",
    id_categoria: 1,
    id_ficha: 1,
    id_proveedor: 4,
    precio_venta: 12000,
    imagen_url: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 230,
    stock_minimo: 50,
    fecha_vencimiento: "2026-09-24",
    estado: "activo",
  },
  {
    id_producto: 14,
    nombre: "Arepa con Semillas de Quinua y Avena x5 und",
    descripcion: "Arepa multicereal ligera y nutritiva elaborada con masa madre de maíz",
    id_categoria: 6,
    id_ficha: 6,
    id_proveedor: 5,
    precio_venta: 8200,
    imagen_url: "https://images.unsplash.com/photo-1509722747041-616f39b57569?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 190,
    stock_minimo: 60,
    fecha_vencimiento: "2026-10-10",
    estado: "activo",
  },
  {
    id_producto: 15,
    nombre: "Arepa con Tocineta y Queso Ahumado x5 und",
    descripcion: "Arepa premium con tocineta crujiente picada y queso campesino ahumado",
    id_categoria: 4,
    id_ficha: 4,
    id_proveedor: 10,
    precio_venta: 12500,
    imagen_url: "https://images.unsplash.com/photo-1644753787067-d62ae70f303d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 95,
    stock_minimo: 50,
    fecha_vencimiento: "2026-09-26",
    estado: "activo",
  },
  {
    id_producto: 16,
    nombre: "Masa de Maíz Amarillo Aliñada x2 kg",
    descripcion: "Masa aliñada con cebolla de rama, color natural y grasa de cerdo",
    id_categoria: 5,
    id_ficha: 7,
    id_proveedor: 4,
    precio_venta: 8500,
    imagen_url: "https://images.unsplash.com/photo-1574484284002-952d92456975?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    stock_actual: 210,
    stock_minimo: 60,
    fecha_vencimiento: "2026-09-21",
    estado: "inactivo",
  },
];

export const getProductos = async () => {
  return [...mockProductos];
};

export const createProducto = async (producto) => {
  const newObj = {
    id_producto: Date.now(),
    estado: 'activo',
    ...producto,
  };
  mockProductos = [newObj, ...mockProductos];
  return newObj;
};

export const updateProducto = async (id_producto, producto) => {
  mockProductos = mockProductos.map((p) => (p.id_producto === id_producto ? { ...p, ...producto } : p));
  return { id_producto, ...producto };
};

export const deleteProducto = async (id_producto) => {
  mockProductos = mockProductos.filter((p) => p.id_producto !== id_producto);
  return true;
};
